from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

out='output/pdf/factory_adjuster_simulation_corrected_plan.pdf'
doc=SimpleDocTemplate(out,pagesize=A4,leftMargin=16*mm,rightMargin=16*mm,topMargin=15*mm,bottomMargin=15*mm)
s=getSampleStyleSheet(); s.add(ParagraphStyle(name='T',parent=s['Title'],fontSize=18,leading=22,alignment=TA_CENTER,textColor=colors.HexColor('#12355B'))); s.add(ParagraphStyle(name='H',parent=s['Heading2'],fontSize=12.5,leading=15,textColor=colors.HexColor('#12355B'),spaceBefore=8,spaceAfter=4)); s.add(ParagraphStyle(name='B',parent=s['BodyText'],fontSize=9.1,leading=12.5,spaceAfter=4)); s.add(ParagraphStyle(name='Sm',parent=s['BodyText'],fontSize=8.2,leading=10.5))
P=lambda x,st='B': Paragraph(x,s[st])
story=[P('Corrected Factory Machine Failure and Adjuster Simulation Plan','T'),P('Verified against the problem statement and meeting notes','B'),Spacer(1,4)]
story += [P('1. Exact interpretation','H'),P('When a machine fails, the service manager assigns it to an available compatible adjuster. Adjusters may have one or more machine-category skills. The original statement describes a single queue that contains waiting machines or idle adjusters; with skill mismatches, the implementation will keep two internal lists and document this as a necessary implementation detail. The logical service rule remains FIFO: scan from the front and select the first compatible item.','B')]
story += [P('2. Failure and repair assumptions','H'),P('For each category, the failure interval is Uniform(0, 2 x MTTF), whose mean is the category MTTF. A machine failure clock runs only while the machine is continuously running. Waiting and repair are downtime; no failure clock runs during those periods. After repair, the machine is treated as as-good-as-new and a new uniform failure interval is generated. Repair-time distribution is not specified in the statement, so it is an input assumption: use category-wise fixed or Uniform(min, max) repair times and report the chosen values.','B')]
story += [P('3. Event logic','H'),P('<b>Failure:</b> mark machine failed; if a compatible idle adjuster exists, assign the front eligible adjuster; otherwise put the machine at the back of the machine waiting list. <b>Repair completion:</b> return the machine to running, schedule a new failure, free the adjuster, then scan the machine queue from its front for the first compatible machine. If none is compatible, place the adjuster in the idle list.','B')]
story += [P('4. Inputs','H')]
rows=[['Input','Meaning'],['Machine counts','Category-wise counts; must support examples such as 200 lathe and 50 turning machines.'],['MTTF','Mean time to failure for each category.'],['Adjuster count','Total adjusters to test.'],['Adjuster skills','Category skills for every adjuster.'],['Repair time','Category-wise fixed or configured random duration.'],['Run controls','Simulation horizon, warm-up period, replications, and random seeds.']]
t=Table([[P(x,'Sm') for x in r] for r in rows],colWidths=[38*mm,136*mm],repeatRows=1); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#12355B')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.3,colors.HexColor('#B8C4D1')),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F3F6F9')]),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4)])); story += [t]
story += [P('5. Metrics','H'),P('Machine utilization = total running time / total observation time. Adjuster utilization = total busy repair time / total observation time. Also report average waiting time, average downtime, queue length, number of failures, and category-wise results. Exclude the warm-up period from reported statistics. Run independent replications with different seeds and report mean values plus confidence intervals.','B')]
story += [P('6. Experiment design','H'),P('Sweep all three factors required by the statement: (1) machine counts by category, (2) number of adjusters, and (3) MTTF/reliability values. Store each scenario and replication result in a simple CSV or database table. The simulator must use category-wise lists or generated objects, so hundreds of machines are supported without changing the algorithm.','B')]
story += [P('7. Optimum adjuster count','H'),P('Define the optimum before running experiments. Recommended criterion: choose the smallest number of adjusters for which average machine utilization is at least 90%, average waiting time is below a chosen limit, and adjuster utilization remains within an acceptable operating range. Alternatively, use a documented cost function combining adjuster cost, machine downtime, and waiting time.','B')]
story += [P('8. Minimal implementation','H'),P('Use a discrete-event simulation with a priority event queue. Python and SimPy are suitable, but the required deliverable is the simulation engine and result tables/graphs; machine learning, ticket workflows, and a full dashboard are outside the problem statement and should be deferred.','B')]
story += [P('9. Development order','H'),P('1) Define category inputs and assumptions. 2) Implement running-only uniform failure clocks. 3) Implement service manager, FIFO-compatible assignment, and repair completion. 4) Add utilization and waiting metrics. 5) Add warm-up, replications, confidence intervals. 6) Run the three-factor experiment and select the optimum adjuster count. 7) Produce utilization-versus-adjusters graphs and the final report.','B')]
story += [P('Core rule','H'),P('Machine failure -> service manager -> compatible available adjuster. If no compatible adjuster is available, the machine waits. On repair completion, the machine runs again and receives a new Uniform(0, 2 x MTTF) failure interval.','B')]
def foot(c,d): c.saveState(); c.setFont('Helvetica',8); c.setFillColor(colors.HexColor('#718096')); c.drawString(16*mm,9*mm,'Corrected Adjuster Simulation Plan'); c.drawRightString(A4[0]-16*mm,9*mm,'Page %d'%d.page); c.restoreState()
doc.build(story,onFirstPage=foot,onLaterPages=foot); print(out)
